version: 2
jobs:
  build:
    docker:
      - image: circleci/buildpack-deps:stretch
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build and push Docker image
          command: |
            declare -A REPOMAP
            REPOMAP[r]='r-env'
            REPOMAP[d]='d-env'
            REPOMAP[base]='ubuntu-base'

            echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin

            echo dockerfile: $IMAGE '->' repo: $REPO
            docker build -t codesignal/opencv:v5.6 opencv
            docker push codesignal/opencv:v5.6
            

workflows:
  version: 2
  build-master:
    jobs:
      - build
