version: 2
jobs:
  build:
    docker:
      - image: circleci/buildpack-deps:stretch
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build and push Docker image
          command: |
            bash build_updated_dockerfiles_dev.sh
workflows:
  version: 2
  build-master:
    jobs:
      - build
